CREATE TABLE entries (
    orderId VARCHAR(50),
    refId VARCHAR(20),
    warehouseId VARCHAR(10),
    courierId VARCHAR(100),
    namedDeliveryDate TIMESTAMP,
    sellingPrice DECIMAL(18, 2),
    isReserved INT,
    deliveryQuotedCost DECIMAL(18, 2),
    calculated INT,
    pointOfService VARCHAR(255),
    basePrice DECIMAL(18, 2),
    quantity INT,
    price DECIMAL(18, 2),
    selectedSla VARCHAR(255),
    entryNumber INT,
    info TEXT,
    deliveryCost DECIMAL(18, 2),
    totalPrice DECIMAL(18, 2),
    isReservedInTOTVS INT,
    costPrice DECIMAL(18, 2), 
    quantityStatus VARCHAR(255), 
    vtexPromotions TEXT, 
    costCenter VARCHAR(255), 
    chosenVendor VARCHAR(255), 
    creationDate DATE, 
    creationTime TIME,  
    modifiedDate DATE,  
    modifiedTime TIME,
    PRIMARY KEY (orderId, refId),
    FOREIGN KEY (refId) REFERENCES variantProducts(refId),
    FOREIGN KEY (warehouseId) REFERENCES warehouse(warehouseId),
    FOREIGN KEY (courierID) REFERENCES courier(courierID)
);