CREATE TABLE [variantProducts] (
    [refId] VARCHAR(20) PRIMARY KEY,
    [name] VARCHAR(255),
    [displayName] VARCHAR(255),
    [commercialId] VARCHAR(50),
    [completeProduct] int,
    [lastValidationDiagnostic] TEXT,
    [weight] FLOAT,
    [height] FLOAT,
    [width] FLOAT,
    [length] FLOAT,
    [packageWeight] FLOAT,
    [packageHeight] FLOAT,
    [packageWidth] FLOAT,
    [packageLength] FLOAT,
    [masterBoxWeight] FLOAT,
    [amountMasterBox] INT,
    [masterBoxHeight] FLOAT,
    [masterBoxLength] FLOAT,
    [masterBoxWidth] FLOAT,
    [dunMasterBox] VARCHAR(50),
    [manufacturerCode] VARCHAR(255),
    [manufacturerName] VARCHAR(100),
    [ean] VARCHAR(20),
    [obsolete] int,
    [outOfLine] int,
    [outOfLineWithArrival] int,
    [onlineDate] DATE,
    [offlineDate] DATE,
    [version] VARCHAR(50),
    [unit] VARCHAR(10),
    [approvalStatus] VARCHAR(50),
    [familyId] VARCHAR(100),
    [lineId] VARCHAR(100),
    [brandId] VARCHAR(50),
    [category] VARCHAR(100),
    [creationDate] DATE,
    [creationTime] TIME,
    [modifiedDate] DATE,
    [modifiedTime] TIME,
    FOREIGN KEY (familyId) REFERENCES [productFamily](familyId),
    FOREIGN KEY (lineId) REFERENCES [productLine](lineId),
    FOREIGN KEY (brandId) REFERENCES [productBrand](brandId)
);