CREATE TABLE [orders] (
    [orderId] VARCHAR(20) PRIMARY KEY,
    [paymentId] VARCHAR(50),
    [customerId] VARCHAR(20),
    [addressId] VARCHAR(50),
    [salesChannelId] int,
    [Origin] VARCHAR(50),
    [AffiliateId] VARCHAR(50),
    [Description] VARCHAR(255),
    [deliveryQuotedCost] DECIMAL(10, 2),
    [invoiceShippedDate] DATETIME,
    [invoiceDeliveryDate] DATETIME,
    [authorizedDate] DATETIME,
    [date] DATETIME,
    [statusUpdatedAt] DATETIME,
    [paymentRefund] INT,
    [paymentRefundAttempts] INT,
    [subtotal] DECIMAL(10, 2),
    [totalDiscounts] DECIMAL(10, 2),
    [status] VARCHAR(100),
    [exportStatus] VARCHAR(50),
    [blockCart] INT,
    [creationDate] DATE,
    [creationTime] TIME,
    [modifiedDate] DATE,
    [modifiedTime] TIME,
    FOREIGN KEY (paymentId) REFERENCES [paymentInfo](paymentId),
    FOREIGN KEY (salesChannelId) REFERENCES [salesChannel](salesChannelId),
    FOREIGN KEY (customerId) REFERENCES [customerData](customerId),
    FOREIGN KEY (addressId) REFERENCES [address](addressId)
);