CREATE TABLE [invoices] (
    [orderId] VARCHAR(20),
    [invoiceNumber] VARCHAR(20),
    [invoiceSerie] VARCHAR(5),
    [establishment] VARCHAR(10),
    [invoiceValue] DECIMAL(10, 2),
    [issuanceDate] DATETIME,
    [orderAuthorizedDate] DATETIME,
    [invoiceUrl] VARCHAR(255),
    [invoiceKey] VARCHAR(100),
    [invoiceSendToVtex] INT,
    [invoiceSedtToSalesforce] INT,
    [xml] INT,
    [volumes] INT,
    [courier] VARCHAR(100),
    [reasonEntry] VARCHAR(255),
    [reasonReturn] VARCHAR(255),
    [status] VARCHAR(50),
    [type] VARCHAR(20),
    [stockReleased] INT,
    [creationDate] DATE,
    [creationTime] TIME,
    [modifiedDate] DATE,
    [modifiedTime] TIME,
    PRIMARY KEY (invoiceNumber, invoiceSerie),
    FOREIGN KEY (orderId) REFERENCES [orders](orderId)
);
