CREATE TABLE [paymentInfo] (
    [paymentId]  VARCHAR(50) PRIMARY KEY,
    [paymentModeId]  VARCHAR(20),
    [Connector]  VARCHAR(255),
    [transactionId]  VARCHAR(50),
    [GiftCardId] VARCHAR(50),
    [duplicate] INT,
    [ReferenceValue]   DECIMAL(10,2),
    [Acquirer]   VARCHAR(50),
    [Installments]     INT,
    [Group]  VARCHAR(50),
    [MerchantName]     VARCHAR(255),
    [paidValue]DECIMAL(10,2),
    [Nsu]  VARCHAR(20),
    [pixRefundId]    VARCHAR(50),
    [saved]  INT,
    [AuthId]  VARCHAR(50),
    [CardHolder] VARCHAR(100),
    [RedemptionCode] VARCHAR(50),
    [Tid]  VARCHAR(50),
    [returnCode]   VARCHAR(50),
    [ExpiryYear] VARCHAR(4),
    [ReturnMessage]   VARCHAR(255),
    [DueDate]  DATETIME,
    [LastDigits] VARCHAR(10),
    [ExpiryMonth]   VARCHAR(2),
    [InstallmentsValue] DECIMAL(10,2),
    [FirstDigits] VARCHAR(10),
    [refund]  VARCHAR(255),
    [creationDate]  DATE,
    [creationTime]  TIME,
    [modifiedDate]  DATE,
    [modifiedTime]  TIME,
    FOREIGN KEY (paymentModeId) REFERENCES [paymentModes](paymentModeId),
);

